// Generated by gencpp from file cube_pos/Robot.msg
// DO NOT EDIT!


#ifndef CUBE_POS_MESSAGE_ROBOT_H
#define CUBE_POS_MESSAGE_ROBOT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseWithCovarianceStamped.h>
#include <geometry_msgs/TwistWithCovarianceStamped.h>

namespace cube_pos
{
    template <class ContainerAllocator>
    struct Robot_
    {
        typedef Robot_<ContainerAllocator> Type;

        Robot_()
                : robot_id(0)
                , pose()
                , twist()  {
        }
        Robot_(const ContainerAllocator& _alloc)
                : robot_id(0)
                , pose(_alloc)
                , twist(_alloc)  {
            (void)_alloc;
        }



        typedef uint8_t _robot_id_type;
        _robot_id_type robot_id;

        typedef  ::geometry_msgs::PoseWithCovarianceStamped_<ContainerAllocator>  _pose_type;
        _pose_type pose;

        typedef  ::geometry_msgs::TwistWithCovarianceStamped_<ContainerAllocator>  _twist_type;
        _twist_type twist;




        typedef boost::shared_ptr< ::cube_pos::Robot_<ContainerAllocator> > Ptr;
        typedef boost::shared_ptr< ::cube_pos::Robot_<ContainerAllocator> const> ConstPtr;

    }; // struct Robot_

    typedef ::cube_pos::Robot_<std::allocator<void> > Robot;

    typedef boost::shared_ptr< ::cube_pos::Robot > RobotPtr;
    typedef boost::shared_ptr< ::cube_pos::Robot const> RobotConstPtr;

// constants requiring out of line definition



    template<typename ContainerAllocator>
    std::ostream& operator<<(std::ostream& s, const ::cube_pos::Robot_<ContainerAllocator> & v)
    {
        ros::message_operations::Printer< ::cube_pos::Robot_<ContainerAllocator> >::stream(s, "", v);
        return s;
    }

} // namespace cube_pos

namespace ros
{
    namespace message_traits
    {



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'cube_pos': ['/home/club_robot/localisation_aruco/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




        template <class ContainerAllocator>
        struct IsFixedSize< ::cube_pos::Robot_<ContainerAllocator> >
                : FalseType
        { };

        template <class ContainerAllocator>
        struct IsFixedSize< ::cube_pos::Robot_<ContainerAllocator> const>
                : FalseType
        { };

        template <class ContainerAllocator>
        struct IsMessage< ::cube_pos::Robot_<ContainerAllocator> >
                : TrueType
        { };

        template <class ContainerAllocator>
        struct IsMessage< ::cube_pos::Robot_<ContainerAllocator> const>
                : TrueType
        { };

        template <class ContainerAllocator>
        struct HasHeader< ::cube_pos::Robot_<ContainerAllocator> >
                : FalseType
        { };

        template <class ContainerAllocator>
        struct HasHeader< ::cube_pos::Robot_<ContainerAllocator> const>
                : FalseType
        { };


        template<class ContainerAllocator>
        struct MD5Sum< ::cube_pos::Robot_<ContainerAllocator> >
        {
            static const char* value()
            {
                return "97526698ef657380e5171dbe39f2e35a";
            }

            static const char* value(const ::cube_pos::Robot_<ContainerAllocator>&) { return value(); }
            static const uint64_t static_value1 = 0x97526698ef657380ULL;
            static const uint64_t static_value2 = 0xe5171dbe39f2e35aULL;
        };

        template<class ContainerAllocator>
        struct DataType< ::cube_pos::Robot_<ContainerAllocator> >
        {
            static const char* value()
            {
                return "cube_pos/Robot";
            }

            static const char* value(const ::cube_pos::Robot_<ContainerAllocator>&) { return value(); }
        };

        template<class ContainerAllocator>
        struct Definition< ::cube_pos::Robot_<ContainerAllocator> >
        {
            static const char* value()
            {
                return "uint8 robot_id\n\
geometry_msgs/PoseWithCovarianceStamped pose\n\
geometry_msgs/TwistWithCovarianceStamped twist\n\
================================================================================\n\
MSG: geometry_msgs/PoseWithCovarianceStamped\n\
# This expresses an estimated pose with a reference coordinate frame and timestamp\n\
\n\
Header header\n\
PoseWithCovariance pose\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseWithCovariance\n\
# This represents a pose in free space with uncertainty.\n\
\n\
Pose pose\n\
\n\
# Row-major representation of the 6x6 covariance matrix\n\
# The orientation parameters use a fixed-axis representation.\n\
# In order, the parameters are:\n\
# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n\
float64[36] covariance\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: geometry_msgs/TwistWithCovarianceStamped\n\
# This represents an estimated twist with reference coordinate frame and timestamp.\n\
Header header\n\
TwistWithCovariance twist\n\
\n\
================================================================================\n\
MSG: geometry_msgs/TwistWithCovariance\n\
# This expresses velocity in free space with uncertainty.\n\
\n\
Twist twist\n\
\n\
# Row-major representation of the 6x6 covariance matrix\n\
# The orientation parameters use a fixed-axis representation.\n\
# In order, the parameters are:\n\
# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n\
float64[36] covariance\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Twist\n\
# This expresses velocity in free space broken into its linear and angular parts.\n\
Vector3  linear\n\
Vector3  angular\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
            }

            static const char* value(const ::cube_pos::Robot_<ContainerAllocator>&) { return value(); }
        };

    } // namespace message_traits
} // namespace ros

namespace ros
{
    namespace serialization
    {

        template<class ContainerAllocator> struct Serializer< ::cube_pos::Robot_<ContainerAllocator> >
        {
            template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
            {
                stream.next(m.robot_id);
                stream.next(m.pose);
                stream.next(m.twist);
            }

            ROS_DECLARE_ALLINONE_SERIALIZER
        }; // struct Robot_

    } // namespace serialization
} // namespace ros

namespace ros
{
    namespace message_operations
    {

        template<class ContainerAllocator>
        struct Printer< ::cube_pos::Robot_<ContainerAllocator> >
        {
            template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cube_pos::Robot_<ContainerAllocator>& v)
            {
                s << indent << "robot_id: ";
                Printer<uint8_t>::stream(s, indent + "  ", v.robot_id);
                s << indent << "pose: ";
                s << std::endl;
                Printer< ::geometry_msgs::PoseWithCovarianceStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
                s << indent << "twist: ";
                s << std::endl;
                Printer< ::geometry_msgs::TwistWithCovarianceStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.twist);
            }
        };

    } // namespace message_operations
} // namespace ros

#endif // CUBE_POS_MESSAGE_ROBOT_H